/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.MethodCall#getSignature <em>Signature</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.MethodCall#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getMethodCall()
 * @model
 * @generated
 */
public interface MethodCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Signature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signature</em>' reference.
   * @see #setSignature(External)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getMethodCall_Signature()
   * @model
   * @generated
   */
  External getSignature();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.MethodCall#getSignature <em>Signature</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signature</em>' reference.
   * @see #getSignature()
   * @generated
   */
  void setSignature(External value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.math.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getMethodCall_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // MethodCall
