name: assignment_1
description: Assignment 1 for the course MDSD @ University of Southern Denmark 2022
version: 1.1.0

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
